development:
  adapter: postgresql
  encoding: unicode
  database: db/development.postgresql
  host: localhost
  pool: 5
  username: blog
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: db/test.postgresql
  pool: 5
  username: blog
  password:

