development:
  adapter: postgresql
  encoding: unicode
  database: db/development.postgresql
  pool: 5
  username: blog
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: db/test.postgresql
  pool: 5
  username: blog
  password:

  production:
  adapter: postgresql
  encoding: unicode
  database: db/production.postgresql
  pool: 5
  username: blog
  password: